version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/esglow
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./database/1_create_tables.sql:/docker-entrypoint-initdb.d/1_create_tables.sql
      - ./database/2_insert_data.sql:/docker-entrypoint-initdb.d/2_insert_data.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
